name: "Release"
on:
  push:
    branches:
      - "release"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libudev-dev libssl-dev libgtk-3-dev webkit2gtk-4.0
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: |
            x86_64-pc-windows-msvc
            x86_64-unknown-linux-gnu
            x86_64-apple-darwin
            aarch64-apple-darwin
      - name: Rust Cache
        uses: swatinem/rust-cache@v2
        with:
          key: ${{ runner.os }}-tauri-${{ hashFiles('**/Cargo.lock') }}
      - name: Build and release the Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # set the release tag by reading the app version from tauri.conf.json
          tagName: gametrc-v${version}
          # set the release name by reading the app name and version from tauri.conf.json
          releaseName: GameTrc v${version}
          # generate a draft release
          releaseDraft: true
          # generate a prerelease
          prerelease: false
